SELECT * FROM COUNTRIES ;
select * from DEPARTMENTS;
select DEPARTMENT_NAME from  DEPARTMENTS;
select DEPARTMENT_NAME, DEPARTMENT_ID from  DEPARTMENTS;

select DEPARTMENT_NAME, DEPARTMENT_ID from DEPARTMENTS;
